feat(dot): add dot check command
I wanted a better error message in CI when readlink failed which just
led to a short bash snippet to iterate over all the symlinks to verify
they exist. Felt like this made sense as a command to dot

Signed-off-by: Greg Folker <gfolker@amperecomputing.com>

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -19,6 +19,7 @@ Commands:
     sync                Sync the local branch with the remote tracking branch.
     info                Print information about the current configuration.
     latest              Use the latest version of dotfiles.
+    check               Check the current installation of dotfiles.
 EOF
 }
 
@@ -59,6 +60,14 @@ function main() {
         ;;
     latest)
         git checkout main && git pull && mise install
+        ;;
+    check)
+        for dotfile in ~/.{aliases,functions,env,vimrc,virc,config/{nvim,git}}; do
+            readlink "$dotfile" || {
+                echo "Failed to read $dotfile" >&2
+                exit 1
+            }
+        done
         ;;
     esac
 
